services:
- type: web
  name: resume-matcher
  env: python
  plan: free
  autoDeploy: true
  envVars:
  - key: HF_HOME
    value: /opt/render/project/.cache/huggingface
  buildCommand: |
    pip install -r requirements.txt
    python -m spacy download en_core_web_sm
    python - <<'PY'
from sentence_transformers import SentenceTransformer
SentenceTransformer("all-MiniLM-L6-v2")
PY
  startCommand: uvicorn app_main:app --host 0.0.0.0 --port $PORT
